version: "3.8"

services:
  db:
    container_name: "pg_dev"
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - networking
    restart: always
networks:
  networking:
    driver: bridge